#!/usr/bin/env python3
from enum import Enum, auto

DEFAULT_PAYLOAD_SIZE = 40000
MAXIMUM_PAYLOAD_SIZE = 100000
MIN_RETRY_DELAY = 1
MAX_RETRY_DELAY =1800

class TransactionStatus(Enum):
    SUCCESS = 0
    FAILURE = -1
    CONNECTION_ERROR = -2


class ClientStatus(Enum):
    NOT_INITIALIZED = auto()
    INITIALIZED = auto()
    CONNECTED = auto()
    DISCONNECTED = auto()


class CommandAckResponseCodes(Enum):
    COMMAND_RECEIVED_ACK_CODE = 1000
    SUCCESSFULLY_EXECUTED = 1001
    EXECUTION_FAILURE = 4000
    METHOD_NOT_FOUND = 4001
    EXECUTING_PREVIOUS_COMMAND = 4002
    INSUFFICIENT_INPUTS = 4003
    DEVICE_CONNECTIVITY_ISSUES = 4004
    PARTIAL_EXECUTION = 4005
    ALREADY_ON_SAME_STATE = 4006


class ConfigAckResponseCodes(Enum):
    CONFIG_RECEIVED_ACK_CODE = 1000
    SUCCESSFULLY_EXECUTED = 1003
    EXECUTION_FAILURE = 4000
    CONFIG_FAILED = 4008
